from typing import Any, Dict, Optional
WORDING = \
	{
		'python_not_supported': 'Python版本不支持，更新 {version} 或更高版本',
		'ffmpeg_not_installed': 'FFMpeg没有安装',
		'install_dependency_help': '选择要安装的依赖项 {dependency} 的变体',
		'skip_venv_help': '跳过虚拟环境检查',
		'source_help': '选择源图片',
		'target_help': '选择目标图片或视频',
		'output_help': '指定输出文件或目录',
		'frame_processors_help': '从可用的帧处理器中进行选择 (选项: {choices}, ...)',
		'frame_processor_model_help': '选择帧处理器的模型',
		'frame_processor_blend_help': '指定帧处理器的融合量',
		'face_debugger_items_help': '指定脸部调试器的选择项 (选项: {choices})',
		'ui_layouts_help': '从可用视图布局中进行选择 (选项: {choices}, ...)',
		'keep_temp_help': '处理后保留临时帧 ',
		'skip_audio_help': '省略目标的音频',
		'face_analyser_order_help': '指定用于脸部分析器的顺序',
		'face_analyser_age_help': '指定用于脸部分析器的年龄',
		'face_analyser_gender_help': '指定用于脸部分析器的性别',
		'face_detector_model_help': '指定用于脸部检测器的模型',
		'face_detector_size_help': '指定用于脸部检测器的大小阈值',
		'face_detector_score_help': '指定用于脸部检测器的分数阈值',
		'face_selector_mode_help': '指定脸部选择器的模式',
		'reference_face_position_help': '指定参照脸的位置',
		'reference_face_distance_help': '指定参照脸和目标脸之间的相似度',
		'reference_frame_number_help': '指定参照帧的编号 ',
		'face_mask_types_help': '从可用的遮罩类型中进行选择  (选项: {choices})',
		'face_mask_blur_help': '指定遮罩的模糊量',
		'face_mask_padding_help': '指定遮罩填充（上、右、下、左）的百分比',
		'face_mask_regions_help': '从可用的口罩区域中进行选择  (选项: {choices})',
		'trim_frame_start_help': '指定提取的起始帧',
		'trim_frame_end_help': '指定提取的结束帧',
		'temp_frame_format_help': '指定用于帧提取的图像格式',
		'temp_frame_quality_help': '指定用于帧提取的图像质量',
		'output_image_quality_help': '指定用于输出图像的质量 ',
		'output_video_encoder_help': '指定用于输出视频的编码器',
		'output_video_preset_help': '指定用于输出视频的预设 ',
		'output_video_quality_help': '指定用于输出视频的质量 ',
		'output_video_resolution_help': '指定用于输出视频的分辨率 ',
		'output_video_fps_help': '指定用于输出视频的每秒帧数（fps） ',
		'video_memory_strategy_help': '指定处理视频内存的策略',
		'system_memory_limit_help': '指定要使用的系统内存量（GB）',
		'execution_providers_help': '从可用的执行程序中进行选择  (选项: {choices}, ...)',
		'execution_thread_count_help': '指定执行线程的数量 ',
		'execution_queue_count_help': '指定执行队列的数量 ',
		'skip_download_help': '忽略自动下载和查找',
		'headless_help': '在无头模式下运行程序 ',
		'log_level_help': '从可用日志等级中进行选择',
		'creating_temp': '创建临时资源',
		'extracting_frames_fps': '使用 {video_fps} fps提取帧 ',
		'analysing': '分析中...',
		'processing': '处理中...',
		'downloading': '下载中...',
		'temp_frames_not_found': '未找到临时帧',
		'compressing_image': '压缩图像中...',
		'compressing_image_failed': '压缩图像失败',
		'merging_video_fps': '合并视频 {video_fps} fps',
		'merging_video_failed': '合并视频失败',
		'skipping_audio': '跳过音频',
		'restoring_audio': '恢复音频中... ',
		'restoring_audio_skipped': '已跳过还原音频 ',
		'clearing_temp': '清除临时资源',
		'processing_image_succeed': '图像处理在 {seconds} 秒内成功',
		'processing_image_failed': '图像处理失败',
		'processing_video_succeed': '视频处理在 {seconds} 秒内成功',
		'processing_video_failed': '视频处理失败',
		'model_download_not_done': '模型的下载尚未完成',
		'model_file_not_present': '模型的文件不存在',
		'select_image_source': '选择源图像的路径 ',
		'select_image_or_video_target': '选择目标图像或视频的路径',
		'select_file_or_directory_output': '选择输出路径的文件或目录 ',
		'no_source_face_detected': '未检测到源图像的脸部 ',
		'frame_processor_not_loaded': '无法加载帧处理器 {frame_proccessor}',
		'frame_processor_not_implemented': '帧处理器 {frame_proccessor}未正确实现',
		'ui_layout_not_loaded': '无法加载视图布局 {ui_layout}',
		'ui_layout_not_implemented': '视图布局 {ui_layout}未正确实现',
		'stream_not_loaded': '无法加载流 {stream_mode}',
		'donate_button_label': '捐赠',
		'start_button_label': '开始',
		'stop_button_label': '结束',
		'clear_button_label': '清除',
		'benchmark_runs_checkbox_group_label': '基准运行',
		'benchmark_results_dataframe_label': '基准结果',
		'benchmark_cycles_slider_label': '基准周期',
		'execution_providers_checkbox_group_label': '执行提供者',
		'execution_thread_count_slider_label': '执行线程数',
		'execution_queue_count_slider_label': '执行队列数',
		'face_analyser_order_dropdown_label': '顺序脸部分析器',
		'face_analyser_age_dropdown_label': '年龄脸部分析器',
		'face_analyser_gender_dropdown_label': '性别脸部分析器',
		'face_detector_model_dropdown_label': '脸部检测器模型',
		'face_detector_size_dropdown_label': '脸部检测器大小',
		'face_detector_score_slider_label': '脸部检测器分数',
		'face_selector_mode_dropdown_label': '脸部选择器模式',
		'reference_face_gallery_label': '参考脸部',
		'reference_face_distance_slider_label': '参考脸相似度',
		'face_mask_types_checkbox_group_label': '遮罩类型',
		'face_mask_blur_slider_label': '遮罩模糊量',
		'face_mask_padding_top_slider_label': '遮罩填充上部',
		'face_mask_padding_bottom_slider_label': '遮罩填充下部',
		'face_mask_padding_left_slider_label': '遮罩填充左部',
		'face_mask_padding_right_slider_label': '遮罩填充右部',
		'face_mask_region_checkbox_group_label': '遮罩区域',
		'video_memory_strategy_dropdown_label': '视频存储策略',
		'system_memory_limit_slider_label': '系统内存限制',
		'output_image_or_video_label': '输出',
		'output_path_textbox_label': '输出路径',
		'output_image_quality_slider_label': '输出图像质量',
		'output_video_encoder_dropdown_label': '输出视频编码器',
		'output_video_preset_dropdown_label': '输出视频预设',
		'output_video_quality_slider_label': '输出视频质量',
		'output_video_resolution_dropdown_label': '输出视频分辨率',
		'output_video_fps_slider_label': '输出视频fps',
		'preview_image_label': '预览',
		'preview_frame_slider_label': '预览帧',
		'frame_processors_checkbox_group_label': '帧处理器',
		'face_swapper_model_dropdown_label': '脸部替换模型',
		'face_enhancer_model_dropdown_label': '脸部增强模型',
		'face_enhancer_blend_slider_label': '脸部增强融合量',
		'frame_enhancer_model_dropdown_label': '帧增强器模型',
		'frame_enhancer_blend_slider_label': '帧增强器融合量',
		'face_debugger_items_checkbox_group_label': '脸部调试器选项',
		'common_options_checkbox_group_label': '选项',
		'temp_frame_format_dropdown_label': '临时帧图片格式',
		'temp_frame_quality_slider_label': '临时帧图片质量',
		'trim_frame_start_slider_label': '裁剪帧开始位置',
		'trim_frame_end_slider_label': '裁剪帧结束位置',
		'source_file_label': '源',
		'target_file_label': '目标',
		'webcam_image_label': '图像捕捉',
		'webcam_mode_radio_label': '图像捕捉模式',
		'webcam_resolution_dropdown': '图像捕捉分辨率',
		'webcam_fps_slider': '图像捕捉帧率',
		'point': '.',
		'comma': ',',
		'colon': ':',
		'question_mark': '?',
		'exclamation_mark': '!'
	}


def get(key: str) -> str:
	return WORDING[key]
